### ISSUE TITLE
[Bug] can't launch betterdiscord installer [LINUX]

### ISSUE THREAD

**Issue by Merulox** [BetterDiscord/Installer#247] opened 2022-02-16 23:50 UTC
**Describe the Bug**
The .AppImage crashes upon launch

**To Reproduce**
1. cd into the .AppImage's directory
2. apply sudo chmod u+x 
3. Run it (./)

**Expected Behavior**
It launches and I get to repair betterdiscord (though I hear discord recently broke it)

**Screenshots**
![image](https://user-images.githubusercontent.com/68356319/154376499-ac7e4275-5d4d-4a1f-88be-4ff57b099e19.png)

**Discord Version**
Stable

```
> ./BetterDiscord-Linux\ \(1\).AppImage
Better Discord Installer 1.1.1
[9660:0216/184725.240723:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    9660 trace trap (core dumped)  ./BetterDiscord-Linux\ \(1\).AppImage`
```

**Comment by nyanpasu64** [comment] 2022-02-28 23:00
`--disable-seccomp-filter-sandbox` might be a more narrowly targeted exception than `--no-sandbox` (unsure if more or less secure than `--disable-gpu-sandbox`).

I found independently that the issue is seccomp blocking glibc 2.35's rseq syscalls (`__NR_rseq`). Out of curiosity, can you link the issue/PR/commits which fixed the bug on Electron 13+? (Is it https://www.electronjs.org/releases/stable?version=13&page=3#13.5.0 mentioning https://github.com/electron/electron/pull/31091 and glibc 2.34?)

**Comment by zerebos** [comment] 2023-03-03 23:56
We have upgrade past this version of electron so it should be merged.

**Closed as completed by zerebos** 2023-03-03 23:56 UTC
Labels: bug
