### ISSUE TITLE
Opening Installer

### ISSUE THREAD

**Issue by GQJIMU** [BetterDiscord/Installer#319] opened 2023-02-18 20:04 UTC
When I open up the file of Better Discord it just doesn't do anything.

You open Better Discord for me to cause this.

**Comment by maenDisease** [comment] 2023-02-18 20:07
Join the [BetterDiscord server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) and see this message https://canary.discord.com/channels/86004744966914048/1019697332910051430

**Comment by RianQuenlin** [comment] 2023-02-23 09:52
How about "Post the message here" instead?

> Join the [BetterDiscord server](https://discord.com/invite/0Tmfo5ZbORCRqbAd) and see this message https://canary.discord.com/channels/86004744966914048/1019697332910051430

**Comment by zerebos** [comment] 2023-03-03 23:51
Duplicate of #302

**Closed as completed by zerebos** 2023-03-03 23:51 UTC
Labels: bug
