### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by sicr0** [BetterDiscord/Installer#185] opened 2021-07-14 10:36 UTC
**Describe the bug**
Installer shows error.

**To Reproduce**
1. Run `betterdiscord` on the terminal.
2. Accept license.
3. Select _Install BetterDiscord_
4. Select _Discord_
5. Error shows up.

**Expected behavior**
It should install.

**Screenshots**
![Screenshot_20210714_073440](https://user-images.githubusercontent.com/49662650/125608414-992e0b57-fbd5-46e8-8fbf-ea104ddbc869.png)

**System Information:**
 - OS: Manjaro Linux
- Discord Version: Stable

**Comment by dav1312** [comment] 2021-07-14 10:56
Duplicate of #174

**Comment by zx18018** [comment] 2021-07-16 12:07
The problem still present.
I download new version from https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix
but error the same
![image](https://user-images.githubusercontent.com/53554340/125944981-d179f42e-c7fb-44f9-86d0-b874856cae2f.png)

**Comment by QbDesu** [comment] 2021-07-16 13:11
@zx18018 that's an your firewall, antivirus, or VPN causing problems.

**Comment by sicr0** [comment] 2021-07-16 13:17
Solved it by installing the AppImage, then everything worked fine

**Closed as completed** 2021-07-16 13:18 UTC
Labels: bug

**Comment by zx18018** [comment] 2021-07-17 08:43
The problem is the same on two different laptops.

**Comment by zx18018** [comment] 2021-07-17 08:46
On the first Windows 10 Home on the second Pro
no antivirus (except for the built-in one) and VPN
