### ISSUE TITLE
stuck in black

### ISSUE THREAD

**Issue by smoky6969** [BetterDiscord/Installer#310] opened 2022-12-14 15:26 UTC
when i open the aps stuck in black
![image](https://user-images.githubusercontent.com/120582662/207637073-b6386ffb-57a5-47eb-931e-29cf131ef4bc.png)

**Comment by tnbhaeufi** [comment] 2022-12-14 18:16
got the same problem. never had that before. Using Radeon RDNA2 graphics card

**Comment by aaxim** [comment] 2022-12-14 20:27
even if you unblock it in properties to bypass with windows virus thing it still does it.

**Comment by The-Mighty-Spoon** [comment] 2022-12-15 02:58
Having the same issue

**Comment by Dethkiller15** [comment] 2022-12-15 15:52
While I had the same issue I did just give up and use the manual install method. I just followed along with the video.
https://cdn.discordapp.com/attachments/1019725965284360283/1042235899246817332/Manualinstall-handbrake.mp4

Here is a link to the page.
https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

**Comment by terax6669** [comment] 2022-12-19 10:40
@Tropix126 @rauenzi @Inve1951
![image](https://user-images.githubusercontent.com/19204073/208407660-ec49b3eb-7ef1-45c4-95ea-9eae2837102e.png)

**Comment by neobenedict** [comment] 2022-12-26 13:36
Same issue.

**Comment by RaySollium99** [comment] 2023-01-02 05:52
Same issue over here

**Comment by Deceron** [comment] 2023-01-20 19:25
same issue still happening

**Comment by noassl** [comment] 2023-01-23 11:54
Which node version are you using? Switching to v17 solved this issue for me.

**Comment by terax6669** [comment] 2023-01-31 11:59
> Which node version are you using? Switching to v17 solved this issue for me.

I don't see how your development environment could impact the release binary, but... I've tried downgrading from 18 to 16 and it did nothing.

**Comment by Johnnycyan** [comment] 2023-02-17 03:02
I have the same issue.

OS: Windows 11 Pro 22H2 Build 22621.1105
GPU: Nvidia RTX 3090
CPU: Ryzen 5950x
RAM: 64GB CL18 3600Mhz

**Comment by Dethkiller15** [comment] 2023-02-17 14:14
> I have the same issue.
> 
> OS: Windows 11 Pro 22H2 Build 22621.1105 GPU: Nvidia RTX 3090 CPU: Ryzen 5950x RAM: 64GB CL18 3600Mhz

Best bet is to go to your betterdiscord folder and delete everything in it but the plugins and themes folders.
then uninstall discord itself and make sure it is 100% uninstalled by making sure the discord folder isnt in appdata. Then reinstall discord and then betterdiscord. Should work. I did the same thing on my system. If it works for you then please tell us.

**Comment by xxtraspicyy** [comment] 2023-03-01 23:13
have attempted the manual install as mentioned in this thread and have also deleted all appdata folders for betterdiscord and discord etc still same issue

**Comment by chrisrtxv** [comment] 2023-03-03 18:47
This is still occurring on the installer for 1.8.5.

**Comment by zerebos** [comment] 2023-03-03 23:50
Duplicate of #302

**Closed as completed by zerebos** 2023-03-03 23:50 UTC
Labels: bug
