### ISSUE TITLE
wrong link opens in browser

### ISSUE THREAD

**Issue by q3dd** [BetterDiscord/Installer#210] opened 2021-09-18 16:04 UTC
When I click the GitHub icon in the installer, then it redirects me to https://github.com/BetterDiscord/BetterDiscor instead of https://github.com/BetterDiscord/BetterDiscor

**Comment by dav1312** [comment] 2021-09-18 16:45
Duplicate of #201

**Closed as completed** 2021-10-19 21:04 UTC
Labels: bug
