### ISSUE TITLE
Better Discord Crashing/ Removing with original Discord

### ISSUE THREAD

**Issue by lxciper** [BetterDiscord/Installer#69] opened 2021-04-05 22:35 UTC
Now listen I've had better discord for about three months? Yeah, but this is my second time having issues with it. This new installer came out and I didn't have a trouble until it opened. it would say "Better Discord seems to have crashed your client, Better Discord had AUTOMATICALLY disabled itself." Now, I'm not smart or anything but it also said, "try removing plugins and restarting discord"....problem is how do I remove the plugins? I removed it from my files, and I cant get into Better discord because it shuts down. Anyways, please help me because I'm actually trying to enjoy Better Discord. Thanks.

**Comment by alaley40** [comment] 2021-04-05 23:31
Bye buy

**Comment by Grip555** [comment] 2021-04-06 01:17
Having the same issue.

**Comment by dav1312** [comment] 2021-04-06 15:46
Duplicate of #17

**Comment by SmokedFEDE** [comment] 2021-04-07 16:55
I got the same problem and I had to re-install discord for 3 times.
Maybe you can just install the old version of BetterDiscord and keep using it without updating.
Hope I helped you.

**Comment by rauenzi** [comment] 2021-04-11 04:09
Try finding and renaming this folder `%appdata%\BetterDiscord`. Then reinstall BD. Your plugins will be backed up to whatever you renamed the folder to.

**Closed** 2021-05-07 00:34 UTC
Labels: bug
