### ISSUE TITLE
Beta Installer doesnt load

### ISSUE THREAD

**Issue by klioxide-lol** [BetterDiscord/Installer#39] opened 2021-04-03 06:32 UTC
Basically what happens, is I try installing BD Beta release installer, and the downloader gets stuck on "Attempting to kill Discord" | "Killing Discord"

![image](https://user-images.githubusercontent.com/80074052/113470594-5b7f5a00-941c-11eb-9fa0-e66583074765.png)

**Comment by rauenzi** [comment] 2021-04-03 07:22
Appears to be a duplicate of #25

**Comment by rauenzi** [comment] 2021-04-03 07:22
Make sure discord is fully closed using task manager before running the installer

**Closed by rauenzi** 2021-04-03 07:22 UTC
Labels: bug
