### ISSUE TITLE
[Linux] Fails to open GPU right after launch

### ISSUE THREAD

**Issue by AnzoDK** [BetterDiscord/Installer#246] opened 2022-02-18 11:25 UTC
When the installer opens, it prints the following to the console and dies.

```
[34749:0218/121847.225734:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```

**To Reproduce**
1. Open Installer on Arch Linux [5.16.10-zen1-1-zen] with Nvidia 510.54 [DKMS]
2. See error

**Expected behavior**
Expected it to install...

**Screenshots**.

**System Information:**
 - OS: Linux
- Discord Version: Stable

**Additional context**
![image](https://user-images.githubusercontent.com/22836283/154673760-af6b7a14-b9cb-431b-8f0f-f76e8bc51311.png)

**EDIT***
The installer starts if its followed by any argument???????????????? (tried `--help` and it randomly worked?!)

**Comment by jakiisheep** [comment] 2022-02-18 12:32
Can confirm/reproduce. Arch Linux, Linux 5.16.10-arch1-1

**Comment by redegg89** [comment] 2022-02-18 17:28
Can reproduce. Not arch-specific, but might be arch-derivative specific. Artix Linux, 5.16.8-artix1-2

**Comment by Lezurex** [comment] 2022-02-18 17:36
Can also confirm. Archlinux 5.16.10-zen1-1-zen with Nvidia 510.54-2.

```
[21064:0218/182825.526836:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
/usr/bin/betterdiscord-installer: line 2: 21064 Trace/breakpoint trap   (core dumped) env BD_SKIP_UPDATECHECK=1 /opt/betterdiscord-installer-bin/betterdiscord-installer "$@"
```

Building from source also produces the same error.

**Comment by Vernoxvernax** [comment] 2022-02-18 19:59
```
Better Discord Installer 1.1.1
[54268:0218/205545.726041:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```
Arch 5.16.10-arch1-1 and Nvidia 510.54

Running the installer as root works as expected.

**Comment by Inve1951** [comment] 2022-02-18 22:45
Duplicate of #247 (**HAS WORKAROUND**), which i just transferred from the BD repo.

**Closed as completed by Inve1951** 2022-02-18 22:45 UTC
Labels: bug
