### ISSUE TITLE
Stuck on starting

### ISSUE THREAD

**Issue by MannuVilasara** [BetterDiscord/Installer#308] opened 2022-12-14 06:55 UTC
when I click the setup it gets started but shows nothing
![image](https://user-images.githubusercontent.com/117009138/207527053-af9bbb47-eea3-4299-a043-0dfac3889a26.png)

**Comment by Zachtopia** [comment] 2022-12-14 07:25
I'm having the exact same issue :(

**Comment by TesenDesk** [comment] 2022-12-14 12:24
Same for me :(

**Comment by tnbhaeufi** [comment] 2022-12-14 18:17
same for me. Radeon RDNA2 (6800)

**Comment by zerebos** [comment] 2023-03-03 23:50
Duplicate of #302

**Closed as completed by zerebos** 2023-03-03 23:50 UTC
Labels: bug
