### ISSUE TITLE
Discord canary fatal bug, launches on crash

### ISSUE THREAD

**Issue by ghost** [BetterDiscord/Installer#169] opened 2021-06-17 22:58 UTC
**Describe the bug**
Discord canary crashes when I start discord, doesn't even load the updater splash

**To Reproduce**
1. Install betterdiscord to discord canary 
2. Launch discord canary
3. See error

**Expected behavior**
Discord canary launces and functions properly

**Screenshots**
[https://i.ibb.co/k0rFDrX/Discord-Canary-asfttv-PRlo.png](https://i.ibb.co/k0rFDrX/Discord-Canary-asfttv-PRlo.png)

**System Information:**
 - OS: Windows
- Discord Version: Canary

**Additional context**
N/A

**Comment by dav1312** [comment] 2021-06-18 13:28
Duplicate of #161
Please keep track of the [other issue](https://github.com/rauenzi/BetterDiscordApp/issues/821) in the BetterDiscordApp repository

**Closed as completed** 2021-07-09 23:08 UTC
Labels: bug
