### ISSUE TITLE
.exe dose not launch

### ISSUE THREAD

**Issue by TheRodrixHD** [BetterDiscord/Installer#46] opened 2021-04-03 09:59 UTC
**Describe the bug**
When I try to launchBetterDiscord.exe does not launch 

https://user-images.githubusercontent.com/68759622/113475135-6bc72180-947c-11eb-8a7d-34d8d624556c.mp4

**Comment by Ynaught** [comment] 2021-04-03 16:07
I am having the same issue. Any specs or something I can offer to help better diagnose the issue?

**Comment by rauenzi** [comment] 2021-04-03 16:24
Check that it was not blocked by whatever antivirus you have installed

**Comment by rauenzi** [comment] 2021-04-03 16:26
Duplicate of #43

**Closed by rauenzi** 2021-04-03 16:26 UTC
Labels: bug
