### ISSUE TITLE
BetterDiscord Installer 'Repair' Function Error

### ISSUE THREAD

**Issue by miguelthemann** [BetterDiscord/Installer#279] opened 2022-08-03 22:37 UTC
**Describe the bug**
Cannot repair Discord using BetterDiscord Installer.

**Screenshots**
![BD_Installer](https://user-images.githubusercontent.com/88190875/182724012-9369d1cf-760b-47cd-8058-5e86419a74ba.png)

**System Information:**
 - OS: Windows 10 Stable 64-Bit (10.0.19044)
- Discord Version: Stable 139803 (12d1af9)

**Additional context**
Installer exits with error Command 'WMIC path win32_process get Name,Processid,ParentProcessId,Commandline,ExecutablePath' terminated with code: 1

**Comment by SmolAlli** [comment] 2022-09-25 04:36
Duplicate of #25

**Closed as completed** 2023-03-03 23:54 UTC
Labels: bug
