### ISSUE TITLE
Please, add snap suport

### ISSUE THREAD

**Issue by rhuangabrielsantos** [BetterDiscord/Installer#123] opened 2021-05-06 13:33 UTC
**Is your feature request related to a problem? Please describe.**
Add snap support for install BetterDiscord in linux, what's a big problem in add support for snaps and flatpack?

**Comment by tropicaaal** [comment] 2021-05-06 15:52
I believe flatpaks work? Unsure though, that would be a question for @rauenzi. As for snap installs, there are some permission issues associated with how discord is installed through snap which requires an alternate injection method. It's on our todo but it's not especially high priority.

**Comment by zerebos** [comment] 2021-05-07 00:32
Flatpak can be handled through manual install. Snap has several issues as Tropix mentioned which will also require changes in the main app to properly handle. It is being tracked there under https://github.com/rauenzi/BetterDiscordApp/issues/679

**Comment by zerebos** [comment] 2021-05-07 00:40
Going to mark this as duplicate of #26

**Closed as completed by zerebos** 2021-05-07 00:40 UTC
Labels: enhancement
