### ISSUE TITLE
Not launching the EXE

### ISSUE THREAD

**Issue by theparaodxdoge** [BetterDiscord/Installer#43] opened 2021-04-03 09:15 UTC
Not much to say. i attempt to open it and it doesn't execute.

https://user-images.githubusercontent.com/43124945/113474082-33e7bc00-9433-11eb-8c00-2b16bd2ba357.mp4

**Comment by TheRodrixHD** [comment] 2021-04-03 09:47
same

**Comment by rauenzi** [comment] 2021-04-03 16:26
Please check that your antivirus is not blocking it from running.

**Comment by rauenzi** [comment] 2021-04-03 16:27
Duplicate of #36

**Closed by rauenzi** 2021-04-03 16:27 UTC

**Comment by theparaodxdoge** [comment] 2021-04-03 19:56
> Please check that your antivirus is not blocking it from running.

its not

**Comment by uber-ate** [comment] 2022-08-04 04:30
anyone find a fix????
