### ISSUE TITLE
didn't run

### ISSUE THREAD

**Issue by DFanso** [BetterDiscord/Installer#40] opened 2021-04-03 07:02 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information:**
 - OS: [e.g. Windows]
- Discord Version: [eg. Stable]

**Additional context**

**Comment by rauenzi** [comment] 2021-04-03 07:23
This provided no information

**Comment by Tropix126** [comment] 2021-04-03 07:29
Not enough information provided. Likely a duplicate of #36.

**Closed by Tropix126** 2021-04-03 07:29 UTC
Labels: bug, invalid

**Comment by kennyhjen** [comment] 2021-04-04 20:46
Chưa hiểu
