### ISSUE TITLE
[Bug] Black stream on instlation Settup

### ISSUE THREAD

**Issue by Pista-afk** [BetterDiscord/Installer#244] opened 2022-01-28 22:34 UTC
**Describe the Bug**

Hi so i Wanted to Donwload Better Discord so i donwloaded it and opened but the screen was only black 
So can Anyone help 

Thanks
**To Reproduce**

**Expected Behavior**

**Screenshots**

<img width="449" alt="image" src="https://user-images.githubusercontent.com/82143750/151630907-c4267b7c-fec6-4863-a211-20eee43e166e.png">

**Discord Version**

**Additional Context**

**Comment by Tecleino** [comment] 2022-01-29 20:57
try installing git and node, it worked for me

**Comment by SmolAlli** [comment] 2022-02-07 11:37
You should join the [Discord Server](https://betterdiscord.app/invite) if you haven't already to have this issue solved. There have been reports of people's AntiVirus causing this (mainly on Win 10)
This is also the wrong repository to be making issues on the installer.

**Comment by GiovanH** [comment] 2022-02-18 05:11
Can confirm, even with git and node installed.

**Comment by GiovanH** [comment] 2022-02-18 05:15
It looks like this is happening when there's a stray discord process around that has a file locked. An error is thrown that isn't handled or checked for.

**Comment by ItsCubeTime** [comment] 2022-06-16 15:16
> It looks like this is happening when there's a stray discord process around that has a file locked. An error is thrown that isn't handled or checked for.

I can confirm this. Closing any Discord processes manually lets you fire up the installer

**Comment by aaxim** [comment] 2023-01-24 23:46
closing all discord apps in task manager didn't work for me ;-; 
![image](https://user-images.githubusercontent.com/120601149/214446158-ccce242e-1f20-45b6-9e5e-bc10c422a55e.png)

**Comment by RealAkim** [comment] 2023-01-28 18:20
I'm having the same issues, I disabled Windows Defender and installed the latest versions of Node and Git but it's still just a black box
![image](https://user-images.githubusercontent.com/123832635/215284175-ff58e54f-61a7-4507-8125-21bfe9fef463.png)

**Comment by bigohi** [comment] 2023-02-02 22:34
Hello guys, I just solved this problem. You will have to manually install betterdiscord.
Follow this documentation on the site, it still pretty simple.
Hope this will work for you too.

https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

**Comment by laagginq** [comment] 2023-02-05 03:28
im having the same problem

**Comment by MLNekit** [comment] 2023-02-17 01:07
> Hello guys, I just solved this problem. You will have to manually install betterdiscord. Follow this documentation on the site, it still pretty simple. Hope this will work for you too.
> 
> https://docs.betterdiscord.app/users/getting-started/installation/#manual-installation

![image](https://user-images.githubusercontent.com/125297721/219523415-e7fbbe79-35cb-4359-9ec7-e756572314af.png)
I tried to install manually but I get this error

**Comment by LULU1422-2** [comment] 2023-02-17 11:16
![image](https://user-images.githubusercontent.com/93459379/219635673-bc63192b-bd26-49ca-9b6e-0cbc7e3dd81e.png)
Getting this error

**Comment by zerebos** [comment] 2023-03-03 23:57
The fix for this has been merged and will be fixed in next release.

**Comment by terax6669** [comment] 2023-03-04 21:44
> The fix for this has been merged and will be fixed in next release.

@rauenzi I can't really see any commits related to this though. What was the issue?

**Comment by zerebos** [comment] 2023-03-04 21:55
It was this commit af8668b251111bc8c0f757d438f0b3ebfda2a072. The error prevented in this commit would happen on startup causing the page to not finish loading.

**Comment by githubisfreestorage** [comment] 2023-03-05 23:21
After some research I found out why it was happening.
Your discord is installed in ProgramData instead of AppData, to fix this you need to reinstall discord or redirect the discord to ProgramData. After you do that it should work.

**Comment by zerebos** [comment] 2023-03-06 07:46
This is not quite correct. It occurs when the `modules` directory is empty. It does not matter if it is in AppData or ProgramData

**Closed as completed** 2023-03-27 13:38 UTC
Labels: bug
