### ISSUE TITLE
License checkbox didn't work

### ISSUE THREAD

**Issue by book777** [BetterDiscord/Installer#215] opened 2021-10-09 11:37 UTC
**Describe the bug**
Checkbox (not label text) click event didn't chance state on the license page

**To Reproduce**
1. Go to license page
2. Click accept license checkbox
4. The checkbox will not change

**Expected behavior**
Change state on click checkbox same as label text

**Screenshots**
![image](https://user-images.githubusercontent.com/4815526/136656444-70385fef-8846-4d8e-9781-fdcadec20ab4.png)

**System Information:**
 - OS: Windows 10 20H2 19042.1266

**Solution**
src/renderer/common/Checkbox.svelte
![image](https://user-images.githubusercontent.com/4815526/136656400-cd8c13f9-ff65-4ef1-ad84-05caf713a3e9.png)

**Comment by dav1312** [comment] 2021-10-09 12:37
Duplicate of #177

**Comment by book777** [comment] 2021-10-09 14:13
Yes, but the problem is steel exists

**Comment by dav1312** [comment] 2021-10-09 20:19
Yes and as you can see the issue #177 is still open...
There is no need to open a new issue about it.
It was already fixed in the dev branch and will be fixed in the next update.

**Comment by zerebos** [comment] 2021-10-19 21:05
This has been fixed in the new release

**Closed as completed by zerebos** 2021-10-19 21:05 UTC
Labels: bug
