### ISSUE TITLE
Unable to click the button.

### ISSUE THREAD

**Issue by Aws0mee** [BetterDiscord/Installer#190] opened 2021-07-18 11:47 UTC
**Describe the bug**
I'm unable to click the button to accept the license agreement, I can only click on the text. This isn't a big issue at all, but I thought I might as well point it out if it's not already known.

**To Reproduce**
Try to click the box, it won't work. Click the text, it will work.

**Expected behavior**
When I click the box it should check it.

**Screenshots**

![button](https://user-images.githubusercontent.com/51889746/126065777-1a2b551b-ff40-43ef-9368-4248b4bf0da7.gif)

**Comment by dav1312** [comment] 2021-07-18 11:49
Duplicate of #177

**Closed as completed** 2021-07-18 15:54 UTC
Labels: bug
