### ISSUE TITLE
Getting a JavaScript error on Canary.

### ISSUE THREAD

**Issue by Alauraa** [BetterDiscord/Installer#161] opened 2021-06-06 17:36 UTC
**Describe the bug**

When you install BD for canary, it errors out with the error being.

" A javaScript error occured in the main process

Uncaught Exception:
TypeError: process.electronBinding is not a function
at
 C:\Users\Username\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\injector.js:1:5940
at Object.<anonymous>
 (C:\Users\Username\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\injector.js:1:6951)
 at Module._compile (internal/modules/cjs/loader.js:1078:30)
 at Object.Module._extensions.js (internal/modules/cjs/loader.js:1108:10)
 at Module.load (internal/modules/cjs/loader.js:935:32)
 at Module._load (internal/modules/cjs/loader.js:776:14)
 at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
 at Module.require (internal/modules/cjs/loader.js:959:19)
 at require (internal/modules/cjs/helpers.js:88:18)
 at Object.<anonymous>
(C:\Users\Username\Appdata\Local\DiscordCanary\app-1.0.35\resources\app\index.js:1:1) "

**To Reproduce**
1. Go to 'to the website, download the installer, run the installer, let it try to restart canary.'
2. 'When it runs canary on the auto-restart, it crashes with the error.'

**Expected behavior**

I expect Discord canary to run without errors and to pop up. 

**Screenshots**

https://blog.fioregaming.com/wp-content/sharex-content/DiscordCanary_o6IpknnkNa.png

**System Information:**
 - OS: Windows Pro x64
- Discord Version: Canary

**Additional context**

Fresh install, no customization, etc, vanilla discord canary.

**Comment by QbDesu** [comment] 2021-06-06 17:38
Duplicate of https://github.com/rauenzi/BetterDiscordApp/issues/821

**Comment by NathanPeake** [comment] 2021-06-08 13:43
any updates on this?

**Comment by dav1312** [comment] 2021-06-08 13:47
> any updates on this?

Please keep track of the [other issue](https://github.com/rauenzi/BetterDiscordApp/issues/821) in the BetterDiscordApp repository

**Comment by Sudowo** [comment] 2021-06-11 00:28
any fixes to this yet? i just want to use betterdiscord D:

**Closed as completed** 2021-06-16 16:18 UTC
Labels: bug
